### ISSUE TITLE
Throttle Limits Exceeded Error 

### ISSUE THREAD

**Issue by amitcorcrm** [beanworks/quickbooks-online-v3-sdk#6]
When I am sending data from my web application to QuickBooks Online using PHP-SDK-V3 and I am getting below errors, can anyone face this error if yes so please help me on this how ca i overcome this issue.

`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<IntuitResponse time="2017-07-30T22:45:22.933-07:00" xmlns="http://schema.intuit.com/finance/v3">
    <Fault type="SERVICE">
        <Error code="3001">
            <Message>message=ThrottleExceeded; errorCode=003001; statusCode=429</Message>
            <Detail>The request limit was reached.  Try again later</Detail>
        </Error>
    </Fault>
</IntuitResponse>`

**Comment by leimd** [comment]
It seems that you are hitting the QBO server too hard, try throttle your request on your server.

**Comment by amitcorcrm** [comment]
@leimd thanks for your reply.  So how can I prevent this thing?

**Comment by leimd** [comment]
Hi @amitcorcrm ,

Intuit API has a rate limit of 500 requests per minute, that means on average you can have 8.33 requests per second. I would then suggest you put `usleep(120)` somewhere in your loop to send request to throttle it. Alternative you can talk to Intuite to try to increase the rate limit for your application.

**Comment by hightowertech** [comment]
it doesnt mean you're hitting the api too hard or coming up to a throttling limit, it means its a giant company with a near monopoly and they have massive bugs that they dont think they have to fix so you have to build your implementation just assuming that it will falsely give you this error at some random interval. its great. almost as great as giving you an "expires" timestamp in the users timezone, but giving you no way to query the users' timezone. everything about the quickbooks api is just grand.
